{% set data= load_setup_py_data() %}
package:
  name: spt3g_cutter
  version: {{environ.get("SPT3G_CUTTER_VERSION", 0.1.0)}}

source:
  git_url: https://github.com/menanteau/spt3g_cutter
  git_rev: tags/{{environ.get("SPT3G_CUTTER_VERSION", 0.1.0)}}

build:
  skip: True #[win]
  script_env:
    - CONDA_PREFIX

  script: python setup.py install --prefix=$CONDA_PREFIX/spt3g_cutter --install-lib=$CONDA_PREFIX/spt3g_cutter/python

requirements:
  build:
    - python
    - fitsio
    - pyyaml
    - astropy
    - sqlite
    - pandas
    - numpy

  run:
    - python
    - fitsio
    - pyyaml
    - astropy
    - sqlite
    - pandas
    - numpy
